export const homeObjeOne = {
    id: 'Tafsiir',
    topLine1:'Tafsiir',
    headline1:'Quran Tafsiir Audio',
    description1: 'By Sh. Umal',
    linkurl1:'tafsiirUmal',
    img1: require('../../images/svg-7.svg').default,
    alt:'qur',
    topLine2:'Tafsiir',
    headline2:'Quran Tafsiir Audio',
    description2: 'By Sh. Umar Farooq',
    img2: require('../../images/svg-7.svg').default,
    linkurl2:'tafsiirFarooq',
    topLine3:'Tafsiir',
    headline3:'Quran Tafsiir Audio',
    description3: 'By Sh. Muhammad Dirir Umar Ali',
    img3: require('../../images/svg-7.svg').default,
    linkurl3:'tafsiirAli',
};

export const homeObjeTwo = {
    id: 'Hadith',
    topLine1:'Hadith',
    headline1:'Mukhtasar Saxiixul Bukhaari',
    description1: 'Lectures on Sahih Bukhari',
    img1: require('../../images/svg-3.svg').default,
    linkurl1:'tafsiirUmal',
    topLine2:'Hadith',
    headline2:'Mukhtasar Saxiixul Muslim',
    description2: 'Lectures on Sahih Muslim',
    img2: require('../../images/svg-3.svg').default,
    linkurl2:'tafsiirUmal',
    topLine3:'Hadith',
    headline3:' Sunan Tirmidi',
    description3: 'Lectures on Sunan Tirmidi',
    img3: require('../../images/svg-3.svg').default,
    linkurl3:'tafsiirUmal',
};

export const homeObjeThree = {
    id: 'Books',
    topLine1:'Islamic Books',
    headline1:'Riyadu Salixiin',
    description1: 'Lectures Focusing on Hadith, Ethics, Worship And More.',
    img1: require('../../images/svg-5.svg').default,
    linkurl1:'tafsiirUmal',
    topLine2:'Islamic Books',
    headline2:'Al-Adab Al-Mufrad',
    description2: 'Addressing the Question of Perfecting Muslim Manners',
    img2: require('../../images/svg-5.svg').default,
    linkurl2:'tafsiirUmal',
    topLine3:'Islamic Books',
    headline3:'Buluqul Miraam',
    description3: 'Lectures on the Hadith Collection Buluqul Miraam',
    img3: require('../../images/svg-5.svg').default,
    linkurl3:'tafsiirUmal',

};
