export const homeObjeOne = {
    id: 'Tafsiir',
    topLine1:'Tafsiir',
    headline1:'Tafsiirka Quraanka',
    description1: 'By Sheikh Maxamad Umal',
    linkurl1:'tafsiirUmal',
    img1: require('../../images/svg-7.svg').default,
    alt:'qur',
    topLine2:'Tafsiir',
    headline2:'Tafsiirka Quraanka',
    description2: 'By Sheikh Cumar Farooq',
    img2: require('../../images/svg-7.svg').default,
    linkurl2:'tafsiirFarooq',
    topLine3:'Tafsiir',
    headline3:'Tafsiirka Quraanka',
    description3: 'By Sheikh Maxamad Dirir Cumar Ali',
    img3: require('../../images/svg-7.svg').default,
    linkurl3:'tafsiirAli',
};

export const homeObjeTwo = {
    id: 'Hadith',
    topLine1:'Xadiiska',
    headline1:'Mukhtasar Saxiixul Bukhaari',
    description1: 'Dhageyso Muxaadaro Ku Saabsan Saxiix Bukhari',
    img1: require('../../images/svg-3.svg').default,
    linkurl1:'hadithBukhari',
    topLine2:'Hadith',
    headline2:'Mukhtasar Saxiixul Muslim',
    description2: 'Dhageyso Muxaadaro Ku Saabsan Saxiix Muslim',
    img2: require('../../images/svg-3.svg').default,
    linkurl2:'hadithMuslim',
    topLine3:'Hadith',
    headline3:' Sunan Tirmidi',
    description3: 'Dhageyso Muxaadaro Ku Saabsan Sunan Tirmidi',
    img3: require('../../images/svg-3.svg').default,
    linkurl3:'hadithTirmidi',
};

export const homeObjeThree = {
    id: 'Books',
    topLine1:'Kutubta Islaamka',
    headline1:'Riyadu Salixiin',
    description1: 'Dhageyso Muxaadaro Ku Saabsan Xadiiska iyo Cibaado.',
    img1: require('../../images/svg-5.svg').default,
    linkurl1:'bookRS',
    topLine2:'Islamic Books',
    headline2:'Buluqul Miraam',
    description2: 'Dhageyso Muxaadaro Ku Saabsan Buuga Buluqul Miraam',
    img2: require('../../images/svg-5.svg').default,
    linkurl2:'bookBM',
    topLine3:'Islamic Books',
    headline3:'Al-Adab Al-Mufrad',
    description3: 'Dhageyso Muxaadaro Ku Saabsan Dhaqanka Muslimka',
    img3: require('../../images/svg-5.svg').default,
    linkurl3:'bookAM',

};
